image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  MYSQL_USER: sureedu
  MYSQL_PASSWORD: sureedu
  MYSQL_DATABASE: sureedurecords
  MYSQL_ROOT_PASSWORD: sureedu-admin


build:
  stage: build
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test:
  stage: test
  image:
    name: $CONTAINER_TEST_IMAGE
    entrypoint: [""]

  services:
    - name: mysql:5.7
      alias: mysqldb
    - name: redis:5-alpine
      alias: redis

  script:
    - python manage.py test

  only:
    - master

release-image:
  stage: release
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
