version: '3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data1:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: sureedurecords
      POSTGRES_USER: sureedu
      POSTGRES_PASSWORD: sureedu

  redis:
    image: redis:5-alpine

  web:
    build: .
    image: registry.gitlab.com/suretradebsl/sureedu-sms/sureedu.service.recordspropersam/sureedu-records
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
      - 5432:5432
      - 6379:6379
    depends_on:
      - postgres

volumes:
  postgres_data1:
