# Generated by Django 2.1.4 on 2018-12-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='Name of the School')),
                ('school_website', models.CharField(max_length=50, verbose_name="School's website")),
                ('about_school', models.TextField(verbose_name='A Little About the School')),
                ('school_address', models.CharField(max_length=120, verbose_name='Address of the School')),
                ('school_phone', models.CharField(max_length=20, unique=True, verbose_name='School Phone number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
