# Generated by Django 2.1.4 on 2018-12-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='Name of the School')),
                ('school_website', models.CharField(max_length=50, verbose_name="School's website")),
                ('about_school', models.TextField(verbose_name='A Little About the School')),
                ('school_address', models.CharField(max_length=120, verbose_name='Address of the School')),
                ('school_phone', models.CharField(max_length=20, unique=True, verbose_name='School Phone number')),
                ('school_logo', models.CharField(default='default_png_logo_address', max_length=125, verbose_name='School Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name="Staff's first name")),
                ('last_name', models.CharField(max_length=25, verbose_name="Staff's Sur Name")),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=5, verbose_name="Teacher's gender")),
                ('phone', models.CharField(max_length=25, verbose_name="Staff's contact phone number")),
                ('email', models.CharField(max_length=50, null=True, verbose_name="Staff's working email")),
                ('profile_pics', models.CharField(blank=True, max_length=50, null=True, verbose_name='profile picture of staff')),
                ('date_employed', models.DateField(blank=True, null=True)),
                ('date_relieved', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='The School that staff belongs to')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
