# Generated by Django 2.1.4 on 2018-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_DataBaseTableSetUp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pics',
            field=models.CharField(blank=True, default='no profile pix uploaded', max_length=50, verbose_name='profile picture of staff'),
        ),
    ]
