# Generated by Django 2.1.4 on 2019-01-28 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_firstMIgration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentachievement',
            old_name='achievements',
            new_name='achievement',
        ),
    ]
