# Generated by Django 2.1.4 on 2018-12-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='group name')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=25, verbose_name='Name of Level')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50, verbose_name='Name of the School')),
                ('school_website', models.CharField(max_length=50, verbose_name="School's website")),
                ('about_school', models.CharField(max_length=255, verbose_name='A Little About the School')),
                ('school_address', models.CharField(max_length=120, verbose_name='Address of the School')),
                ('school_phone', models.CharField(max_length=20, verbose_name='School Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=25, verbose_name='Name of Session')),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.School', verbose_name='The Related School')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Name of School subject')),
                ('description', models.CharField(max_length=255)),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.School', verbose_name='related school')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'FIRST TERM'), (2, 'SECOND TERM'), (3, 'THIRD TERM')], verbose_name='term type')),
                ('start_date', models.DateField(verbose_name='Starting of term date')),
                ('end_date', models.DateField(verbose_name='Ending of term date')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Session', verbose_name='related session')),
            ],
        ),
        migrations.AddField(
            model_name='level',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Session', verbose_name='related session for level'),
        ),
        migrations.AddField(
            model_name='group',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Level', verbose_name='related level for group'),
        ),
    ]
