# Generated by Django 2.1.4 on 2018-12-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_DataBaseTableSetUp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='The name of the achievement')),
                ('value', models.IntegerField(verbose_name='The numeric value attached to this achievement')),
                ('description', models.TextField(verbose_name='A Description of the achievement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, unique=True, verbose_name='group name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=25, unique=True, verbose_name='Name of Level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=25, verbose_name='Name of Session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='The Related School')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True, verbose_name='Name of School subject')),
                ('description', models.TextField(null=True, verbose_name='Short description for subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='record.Group', verbose_name='groups offering subject')),
                ('levels', models.ManyToManyField(to='record.Level', verbose_name='levels offering subject')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='School where subject is offered')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(choices=[(1, 'FIRST TERM'), (2, 'SECOND TERM'), (3, 'THIRD TERM')], verbose_name='term type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Starting of term date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ending of term date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='related school')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Term', verbose_name='term in which subject is offered'),
        ),
        migrations.AddField(
            model_name='level',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Session', verbose_name='related session for level'),
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Level', verbose_name='level that group belongs to'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='record.Level', verbose_name='The level that the achievement belongs to'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='School where the achievement exists'),
        ),
    ]
