# Generated by Django 2.1.4 on 2018-12-08 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20181208_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_levels',
            new_name='levels',
        ),
    ]
