# Generated by Django 2.1.4 on 2018-12-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_auto_20181208_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='session_id',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='term',
            old_name='session_id',
            new_name='session',
        ),
    ]
