# Generated by Django 2.1.5 on 2019-03-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190128_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='school_organisation_id',
            field=models.PositiveIntegerField(verbose_name='The School Organisation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/student', verbose_name='Student profile picture'),
        ),
    ]
