# Generated by Django 2.1.4 on 2018-12-17 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_DataBaseTableSetUp'),
        ('school', '0001_DataBaseTableSetUp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Parent Full name')),
                ('phone_num', models.CharField(max_length=20, verbose_name='Parent contact number')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent Email Address')),
                ('home_addr', models.TextField(verbose_name='Home Address')),
                ('emergency_numbers', models.TextField(max_length=50, verbose_name='Enter comma separated numbers in case of emergency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_tag', models.CharField(blank=True, max_length=20, null=True, verbose_name="Student's Unique ID tag (produced after successful enrolment)")),
                ('first_name', models.CharField(max_length=25, verbose_name='Students first name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Students Surname')),
                ('current_level', models.CharField(blank=True, max_length=20, null=True, verbose_name="The Student's current level")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrolled_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Level', verbose_name='The Level student was first Enrolled In')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School', verbose_name='The School where the student belongs')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Achievement', verbose_name='Achievement gotten by student')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupil.Student', verbose_name='Related student')),
            ],
            options={
                'db_table': 'student_achievement',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pupil.Student', verbose_name='Students belonging to this parent'),
        ),
    ]
