# Generated by Django 2.1.4 on 2018-12-19 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pupil', '0001_DataBaseTableSetUp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrolled_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Level', verbose_name='The Level student was first Enrolled In'),
        ),
    ]
