# Generated by Django 2.1.4 on 2018-12-19 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_DataBaseTableSetUp'),
        ('pupil', '0002_auto_20181219_0636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_level',
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='record.Level', verbose_name="The Student's current level"),
        ),
    ]
